# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: Build
          command: gradle build --no-daemon
      - run:
          name: Test
          command: gradle test

workflows:
  build-and-test:
    jobs:
      - build-and-test